In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [4]:
data = pd.read_csv("Churn_Modelling.csv")
data

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [5]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis = 1)

In [7]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [9]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns = onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
data =pd.concat([data.drop('Geography', axis = 1),geo_encoded_df], axis = 1)
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [11]:
X = data.drop('EstimatedSalary', axis =1)
y = data['EstimatedSalary']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state= 42)

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
with open('label_encoder_gender_regression.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo_regression.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler_regression.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Regression Problem Statement

In [16]:

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
model = Sequential([
    Dense(64, activation = 'relu', input_shape = (X_train.shape[1],)),
    Dense(32, activation = 'relu'),
    Dense(1)
])

model.compile(optimizer = 'adam', loss = 'mean_absolute_error', metrics = ['mae'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%M%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq =1)

In [22]:
early_Stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 10, restore_best_weights = True)

In [23]:
history = model.fit(
    X_train, y_train,
    validation_data = (X_test, y_test),
    epochs = 100,
    callbacks = [early_Stopping_callback, tensorboard_callback]
)

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99682.2812 - mae: 99682.2812 - val_loss: 97096.2422 - val_mae: 97096.2422
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97159.1250 - mae: 97159.1250 - val_loss: 93374.7422 - val_mae: 93374.7422
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 92136.2109 - mae: 92136.2109 - val_loss: 87079.1406 - val_mae: 87079.1406
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 84715.7812 - mae: 84715.7812 - val_loss: 78813.6406 - val_mae: 78813.6406
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 75857.0312 - mae: 75857.0312 - val_loss: 70068.8594 - val_mae: 70068.8594
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 67118.7188 - mae: 67118.7188 - val_loss: 62245.7930 - val_mae: 62245.7930
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 59862.4023 - mae: 59862.4023 - val_loss: 56404.3750 - val_mae: 56404.3750
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54953.8867 - mae: 54953.8867 - val_loss: 52926.8320 - val_mae: 52926.8320
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52258.8750 - mae: 52258.8750 - val_loss: 51286.2305 - val_mae: 51286.2305
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51003.7852 - mae: 51003.7852 - val_loss: 50707.7266 - val_mae: 50707.7266
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50487.7969 - mae: 50487.7969 - val_loss: 50541.4727 - val_mae: 50541.4727
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50274.0664 - mae: 50274.0664 - val_loss: 50488.0000 - val_mae: 50488.0000
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50176.9492 - mae: 50176.9492 - val_loss: 50453.5898 - val_mae: 50453.5898
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50119.3477 - mae: 50119.3477 - val_loss: 50423.0430 - val_mae: 50423.0430
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50073.3594 - mae: 50073.3594 - val_loss: 50397.2852 - val_mae: 50397.2852
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50032.8984 - mae: 50032.8984 - val_loss: 50374.3633 - val_mae: 50374.3633
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49997.4336 - mae: 49997.4336 - val_loss: 50347.0469 - val_mae: 50347.0469
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49965.3945 - mae: 49965.3945 - val_loss: 50332.4492 - val_mae: 50332.4492
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49936.2227 - mae: 49936.2227 - val_loss: 50317.6953 - val_mae: 50317.6953
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49909.1562 - mae: 49909.1562 - val_loss: 50301.4883 - val_mae: 50301.4883
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49882.2539 - mae: 49882.2539 - val_loss: 50298.1992 - val_mae: 50298.1992
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49861.1836 - mae: 49861.1836 - val_loss: 50288.4219 - val_mae: 50288.4219
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49840.5547 - mae: 49840.5547 - val_loss: 50270.5000 - val_mae: 50270.5000
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49818.2305 - mae: 49818.2305 - val_loss: 50269.5312 - val_mae: 50269.5312
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49805.1719 - mae: 49805.1719 - val_loss: 50263.5234 - val_mae: 50263.5234
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49781.2148 - mae: 49781.2148 - val_loss: 50248.7773 - val_mae: 50248.7773
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49767.1094 - mae: 49767.1094 - val_loss: 50244.6758 - val_mae: 50244.6758
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49754.0039 - mae: 49754.0039 - val_loss: 50238.0664 - val_mae: 50238.0664
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49735.6211 - mae: 49735.6211 - val_loss: 50230.3398 - val_mae: 50230.3398
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49719.8281 - mae: 49719.8281 - val_loss: 50223.6289 - val_mae: 50223.6289
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49708.1797 - mae: 49708.1797 - val_loss: 50230.7031 - val_mae: 50230.7031
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49693.2109 - mae: 49693.2109 - val_loss: 50221.5391 - val_mae: 50221.5391
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49681.1836 - mae: 49681.1836 - val_loss: 50222.2227 - val_mae: 50222.2227
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49667.7461 - mae: 49667.7461 - val_loss: 50213.6914 - val_mae: 50213.6914
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49658.0195 - mae: 49658.0195 - val_loss: 50220.2695 - val_mae: 50220.2695
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49644.3203 - mae: 49644.3203 - val_loss: 50216.8320 - val_mae: 50216.8320
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49634.5781 - mae: 49634.5781 - val_loss: 50213.7773 - val_mae: 50213.7773
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49620.8633 - mae: 49620.8633 - val_loss: 50212.0312 - val_mae: 50212.0312
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49614.8789 - mae: 49614.8789 - val_loss: 50208.8555 - val_mae: 50208.8555
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49601.3555 - mae: 49601.3555 - val_loss: 50205.3633 - val_mae: 50205.3633
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49591.1758 - mae: 49591.1758 - val_loss: 50210.9766 - val_mae: 50210.9766
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49581.0156 - mae: 49581.0156 - val_loss: 50213.0352 - val_mae: 50213.0352
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49573.4570 - mae: 49573.4570 - val_loss: 50203.8320 - val_mae: 50203.8320
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49566.0938 - mae: 49566.0938 - val_loss: 50204.1172 - val_mae: 50204.1172
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49557.2617 - mae: 49557.2617 - val_loss: 50211.8320 - val_mae: 50211.8320
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49548.2695 - mae: 49548.2695 - val_loss: 50210.9023 - val_mae: 50210.9023
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49544.4844 - mae: 49544.4844 - val_loss: 50202.5469 - val_mae: 50202.5469
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49532.8203 - mae: 49532.8203 - val_loss: 50208.7695 - val_mae: 50208.7695
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49526.3047 - mae: 49526.3047 - val_loss: 50213.8125 - val_mae: 50213.8125
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49519.3633 - mae: 49519.3633 - val_loss: 50211.9531 - val_mae: 50211.9531
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49512.3516 - mae: 49512.3516 - val_loss: 50205.2188 - val_mae: 50205.2188
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49505.4219 - mae: 49505.4219 - val_loss: 50208.7109 - val_mae: 50208.7109
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49498.4570 - mae: 49498.4570 - val_loss: 50219.2695 - val_mae: 50219.2695
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49490.7109 - mae: 49490.7109 - val_loss: 50215.1523 - val_mae: 50215.1523
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49487.0117 - mae: 49487.0117 - val_loss: 50226.2305 - val_mae: 50226.2305
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49481.6016 - mae: 49481.6016 - val_loss: 50226.5469 - val_mae: 50226.5469
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49473.8242 - mae: 49473.8242 - val_loss: 50223.1484 - val_mae: 50223.1484

In [24]:
%load_ext tensorboard

In [28]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6007 (pid 26712), started 0:00:08 ago. (Use '!kill 26712' to kill it.)

In [29]:
## Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Tets MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50202.5469 - mae: 50202.5469
Tets MAE : 50202.546875

In [30]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.